name: butterfly
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.4
  provider: ^5.0.0
  url_launcher: ^6.0.4
  convex_bottom_bar: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: BrandIcons
      fonts:
        - asset: fonts/BrandIcons.ttf
#  Typicons, (c) Stephen Hutchings 2012
#        Author:    Stephen Hutchings
#        License:   SIL (http://scripts.sil.org/OFL)
#        Homepage:  http://typicons.com/
#  Font Awesome 4, Copyright (C) 2016 by Dave Gandy
#        Author:    Dave Gandy
#        License:   SIL ()
#        Homepage:  http://fortawesome.github.com/Font-Awesome/
#  Font Awesome 5, Copyright (C) 2016 by Dave Gandy
#        Author:    Dave Gandy
#        License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
#        Homepage:  http://fortawesome.github.com/Font-Awesome/
